'socket.io':
  - versions: "^2"
    peerDependencies: socket.io-client@^2
    commands:
      - npm list socket.io || true
      - yarn test

  - versions: "^3.0.1"
    peerDependencies: socket.io-client@^3
    commands:
      - npm list socket.io || true
      - yarn test

  - versions: "^4"
    peerDependencies: socket.io-client@^4
    commands:
      - npm list socket.io || true
      - yarn test
