'socket.io':
  - versions: "^2"
    peerDependencies: socket.io-client@^2
    commands:
      - echo 'motti'

  - versions: "^3"
    peerDependencies: socket.io-client@^3
    commands:
      - echo 'motti'

  - versions: "^4"
    peerDependencies: socket.io-client@^4
    commands:
      - echo 'motti'
