'socket.io':
  - versions: "2.4.1"
    peerDependencies: socket.io-client@^2
    commands:
      - npm list || true
      - yarn test || true

  - versions: "3.1.2"
    peerDependencies: socket.io-client@^3
    commands:
      - npm list || true
      - yarn test || true

  - versions: "4.1.2 || 4.5.1"
    peerDependencies: socket.io-client@^4
    commands:
      - npm list || true
      - yarn test || true
